services:
  - type: web
    name: linkedin-scraper
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    
    # Environment variables
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_DEBUG
        value: "false"
      - key: DISPLAY
        value: :99
      - key: DISABLE_HEADLESS_WARNING
        value: "true"
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: linkedin-scraper-db
          property: connectionString

databases:
  - name: linkedin-scraper-db
    databaseName: linkedin_companies
    user: linkedin_user
    plan: free
